### ISSUE TITLE
VS2013 compiler support

### ISSUE THREAD

**Issue by ihormelnyk** [Blosc/hdf5-blosc#1]
Please add Visual Studio 2013 compiler support.
See attached patch.
Thanks

From 10712d0523bc142c8ae4217520ca4d214fd4ba06 Mon Sep 17 00:00:00 2001
From: "Ihor.Melnyk" 1@1.com
Date: Mon, 6 Jul 2015 11:09:45 +0300
Subject: [PATCH] VS2013 support

---

 CMakeLists.txt     | 4 ++--
 src/blosc_filter.c | 2 +-
 src/blosc_filter.h | 2 +-
 3 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0393ea4..05d41a1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -44,11 +44,11 @@ include_directories(${HDF5_INCLUDE_DIRS})

 # add blosc libraries
 add_library(blosc_shared SHARED IMPORTED)
-set_property(TARGET blosc_shared PROPERTY IMPORTED_LOCATION ${BLOSC_INSTALL_DIR}/lib/libblosc.so)
+set_property(TARGET blosc_shared PROPERTY IMPORTED_IMPLIB ${BLOSC_INSTALL_DIR}/lib/libblosc.lib)
 add_dependencies(blosc_shared project_blosc)
 include_directories(${BLOSC_INSTALL_DIR}/include)

-add_library(blosc_filter_shared ${SOURCES})
+add_library(blosc_filter_shared SHARED ${SOURCES})
 set_target_properties(
   blosc_filter_shared PROPERTIES OUTPUT_NAME blosc_filter)
 target_link_libraries(blosc_filter_shared blosc_shared ${HDF5_LIBRARIES})
diff --git a/src/blosc_filter.c b/src/blosc_filter.c
index 3ab5237..35e9254 100644
--- a/src/blosc_filter.c
+++ b/src/blosc_filter.c
@@ -20,7 +20,7 @@

 #if H5Epush_vers == 2
 /\* 1.8.x _/
-#define PUSH_ERR(func, minor, str...) H5Epush(H5E_DEFAULT, **FILE**, func, **LINE**, H5E_ERR_CLS, H5E_PLINE, minor, str)
+#define PUSH_ERR(func, minor, str,...) H5Epush(H5E_DEFAULT, **FILE**, func, **LINE**, H5E_ERR_CLS, H5E_PLINE, minor, str)
 #else
 /_ 1.6.x */
 #define PUSH_ERR(func, minor, str) H5Epush(**FILE**, func, **LINE**, H5E_PLINE, minor, str)
diff --git a/src/blosc_filter.h b/src/blosc_filter.h
index 4c3b386..8dc9dce 100644
--- a/src/blosc_filter.h
+++ b/src/blosc_filter.h
@@ -15,7 +15,7 @@ extern "C" {
 #define FILTER_BLOSC 32001

 /\* Register the filter with the library _/
-int register_blosc(char *_version, char *_date);
+__declspec(dllexport) int register_blosc(char *_version, char **date);

 #ifdef __cplusplus
##  }

1.9.5.msysgit.1

**Comment by esc** [comment]
If you could submit the patch as a pull-request that would make it easier to merge.

**Comment by ihormelnyk** [comment]
I've thought about that. But there are changes which makes me able to compile using VS2013 only. I think there should be some general solution for all compilers using some cmake conditions. I'm not very good in cmake and I've fixed only my case.

**Comment by FrancescAlted** [comment]
Yes, testing a solution that is compatible with a range of Visual Studio compilers is desirable.  For example, Python 2.7 is still largely used, and that requires VS 2008.  I know that this is a PITA, but that's how it goes.  I suppose that a first step would be to setup an appveyor config file that allows for a number of Visual Studio compilers.
