### ISSUE TITLE
Question: A one for all HDF5 filter plugin?

### ISSUE THREAD

**Issue by vasole** [Blosc/hdf5-blosc#10]
Hello,

I have managed to compile an HDF5 LZ4 filter plugin for using it with python under windows. However, I was wondering if the same could be achieved using the blosc plugin. In other words, is it possible to use the blosc plugin to handle _reading_ of LZ4 and/or bit shuffled data just by adding it to the HDF5_PLUGIN_PATH?

Thank you.

**Comment by FrancescAlted** [comment]
Ei Armando.  I have no experience with the HDF5 LZ4 filter plugin, but I'm afraid that the Blosc one will be incompatible with it.  The reason is that Blosc has its own format, and that makes compatibility difficult.
