### ISSUE TITLE
Output buffer size guess (cd_values[3]) not used?

### ISSUE THREAD

**Issue by estan** [Blosc/hdf5-blosc#11]
Hi,

It looks to me like `cd_values[3]` which is stored in `outbuf_size` in `blosc_filter(...)` is never actually used: In the compression case, an output buffer exactly as long as the input data is used instead, and in the decompression case the appropriate output buffer size is taken from the buffer header using `blosc_cbuffer_sizes(...)`.

This makes the two debug printouts

``` c
#ifdef BLOSC_DEBUG
        fprintf(stderr, "Blosc: Compress %zd chunk w/buffer %zd\n",
        nbytes, outbuf_size);
#endif
```

and

``` c
#ifdef BLOSC_DEBUG
        fprintf(stderr, "Blosc: Decompress %zd chunk w/buffer %zd\n", nbytes, outbuf_size);
#endif
```

slightly misleading, since those are done when `outbuf_size` still holds the guessed value from `cd_values[3]`.

I could be missing something, but I think both those printouts should be moved a little further down, until after the `outbuf_size` has been overwritten?

**Comment by FrancescAlted** [comment]
Yes, you are totally right.  Would you mind sending a PR for this?  Thanks for reporting anyway.

**Comment by estan** [comment]
I made a [pull request](https://github.com/Blosc/hdf5-blosc/pull/12).

Another question out of curiosity: `cd_values[0]` and `cd_values[1]` are not used either, right? I'm currently setting them to 0 in the code I have which uses this filter.

**Comment by FrancescAlted** [comment]
Your PR has been merged, thanks.

The cd_values 0 and 1 should be set in the [blosc_set_local](https://github.com/Blosc/hdf5-blosc/blob/master/src/blosc_filter.c#L74) function, but I recognize that I am not sure if this is called per every chunk.

**Comment by estan** [comment]
Aha. I think I understand. I'm currently using the filter as plugin to HDF5, installed to `/usr/local/hdf5/lib/plugin`, and using it through h5py with something like this:

``` python
import h5py

# Blosc filter number
BLOSC_FILTER = 32001

# Codes for Blosc shuffling
BLOSC_NOSHUFFLE = 0  # No shuffle
BLOSC_SHUFFLE = 1    # Byte-wise shuffle
BLOSC_BITSHUFFLE = 2 # Bit-wise shuffle

# Codes for compressors shipped with Blosc
BLOSC_BLOSCLZ = 0
BLOSC_LZ4 = 1
BLOSC_LZ4HC = 2
BLOSC_SNAPPY = 3
BLOSC_ZLIB = 4
BLOSC_ZSTD = 5

def blosc_opts(compressor=BLOSC_BLOSCLZ, level=9, shuffle=BLOSC_SHUFFLE, datatype_size=0):
    """Create a compression_opts tuple for Blosc compression"""
    return (0, 0, datatype_size, 0, level, shuffle, compressor) # Element 0, 1, 3 unused

with h5py.File('h5py-example.hdf5', 'w') as outfile:
    outfile.create_dataset(
        'example',
        shape=(3, 3),
        data=[0, 1, 2, 3, 4, 5, 6, 7, 8],
        dtype='float32',
        shuffle=False,
        compression=BLOSC_FILTER,
        compression_opts=blosc_opts(
            compressor=BLOSC_LZ4,
            level=9,
            datatype_size=4
        )
    )

with h5py.File('h5py-example.hdf5', 'r') as infile:
    print(infile['example'].value)
```

As you can see, I'm always passing 0 for element 0, 1 and 3. Hope that's OK, I haven't had any ill effects so far at least.

**Comment by FrancescAlted** [comment]
Well, if that works for you then I suppose you don't have to worry about it anymore ;)  Thanks for the example for others to use.
