### ISSUE TITLE
h5repack issues

### ISSUE THREAD

**Issue by ashishsinghal123** [Blosc/hdf5-blosc#16]
`h5repack --filter UD=32001,7,0,0,0,0,9,0,0 input.h5 output_blosc.h5`

I'm getting this error:

> h5repack error: <input.h5> could not copy data to: output_blosc.h5

 I can successfully use the filter from c++ code. I've upgraded to hdf5 1.8.18 (to fix the h5repack parse issues reported in other threads).

Any idea how to debug the issue? My HD5_PLUGIN_PATH is set correctly and I can see the library is loaded with strace.

**Comment by mkitti** [comment]
I encountered a similar issue.

Try using `h5repack-shared[.exe] --filter UD=32001,7,0,0,0,0,9,0,0 input.h5 output_blosc.h5`

https://forum.hdfgroup.org/t/h5repack-error-with-compression-filter-id-32016/4498/5

**Comment by FrancescAlted** [comment]
Apparently this was fixed in HDF5 1.8.18. Closing.
