### ISSUE TITLE
Enable travis-CI / AppVeyor builds

### ISSUE THREAD

**Issue by jack-pappas** [Blosc/hdf5-blosc#18]
@FrancescAlted Travis CI builds aren't enabled for this repository, and I don't have admin rights to enable it -- would you mind enabling them?

Please also enable the AppVeyor builds too so we can also test the builds on Windows; I've already copied over the ``appveyor.yml`` from c-blosc, so you just need to enable the builds.

Motivation: I tried to run the build for this repo recently and found it was broken (on Windows). If you enable the CI builds, I'll work on fixing the build scripts and CI scripts to get things working again.

**Comment by FrancescAlted** [comment]
Hi Jack.  Thanks for volunteering.  Travis CI and ApVeyor are already enabled.

**Comment by FrancescAlted** [comment]
BTW, Travis-CI builds where enabled already:

https://travis-ci.org/Blosc/hdf5-blosc

so not sure why you don't see them.

**Comment by jack-pappas** [comment]
Very odd -- when I went to that same page yesterday, the builds were definitely not enabled (and it said as much). Thanks anyway 🙂
