### ISSUE TITLE
h5repack with blosc multicore compression

### ISSUE THREAD

**Issue by Castellor** [Blosc/hdf5-blosc#20]
I'm using hdf5-1.10.5 on windows with installed hdf5plugins-1.10.5 and tried to set the env BLOSC_NTHREADS = 10 but only one core is used.

I want to compress images with CHUNK=1x140x160. 

What else has to be done to get multicore support?

**Comment by FrancescAlted** [comment]
With just 22400 items, your chunk seems too small for blosc to split it in different blocks (the only way to leverage multithreading).  Try with something that is at least 512 KB or more (up to your L3 cache size, typically 4 MB or 8 MB).

**Comment by Castellor** [comment]
ok thanks, but maybe I have a more fundamental problem. The download from https://www.hdfgroup.org/downloads/hdf5/ with the plugins reads "hdf5plugin-1.10.5_decode-win10_64-vs15", so I have to build my own with encoding enabled, right?
so i have to build (Windows 10): 
- "hdf5-blosc" and "c-blosc" or "c-blosc2"
