### ISSUE TITLE
Blosc is not installed together by cmake install

### ISSUE THREAD

**Issue by hn-sl** [Blosc/hdf5-blosc#28]
libH5Zblosc.so  generated by cmake build depends on libblosc.so built from github source code as indicated below in CMakeLists.txt.

https://github.com/Blosc/hdf5-blosc/blob/bd8ee59708f366ac561153858735165d3a543b18/CMakeLists.txt#L25-L30

But running cmake installation command ( `cmake --build . --target install`) doesn't install the libblosc.so together  so the installed libH5Zblosc.so  depends on existing libblosc.so on system rather than the shared object built from source code.  Is this intended?

**Comment by FrancescAlted** [comment]
I guess this is intended, yes.  If you can come with a better solution, please contribute it.
