### ISSUE TITLE
incorrect cmake dependency on MacOS/Windows

### ISSUE THREAD

**Issue by stevengj** [Blosc/hdf5-blosc#5]
Currently the `CMakeLists.txt` file depends on `libblosc.so` [here](https://github.com/Blosc/hdf5/blob/fe5ac53050d07c23173bcb8687b85b365acf4620/CMakeLists.txt#L47).  This causes the build to fail on Mac (or presumably Windows) where the library file is `libblosc.dylib` (or `libblosc.dll`).

**Comment by FrancescAlted** [comment]
Fixed by PR #8.
