### ISSUE TITLE
Implement a lock when more than 1 thread is used

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/hdf5-blosc#7]
Starting with blosc 1.5.0, there is not a global lock inside blosc any longer, so this create troubles when using HDF5 in multithreaded environments. Until a lock is created inside this wrapper when calling blosc, keep using blosc < 1.5 seems the safest approach.

For more info, see https://github.com/PyTables/PyTables/issues/437.

**Comment by andreabedini** [comment]
HDF5 should have its own thread lock, perhaps blosc can ride that?

**Comment by FrancescAlted** [comment]
Agreed, in case HDF5 has its own lock, we should use that one.  And the lock should be put in the Blosc/hdf5 package, yes, not in Blosc/c-blosc itself.

**Comment by aldanor** [comment]
Would it be possible then to use multi-threaded blosc compression/decompression?

**Comment by FrancescAlted** [comment]
Yes, I think so.

**Comment by FrancescAlted** [comment]
https://github.com/Blosc/c-blosc/commit/6c8142ed2325460e9992adca5cad913ffd02765c adds the missing lock, so using latest C-Blosc (currently at 1.8.1) should fix this.  So I think we can close this one now.
