### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by toddrme2178** [Blosc/hdf5-blosc#9]
Is there a plan to have a release for this package?  I want to package it, but that is hard to do without a specific release to target.

**Comment by FrancescAlted** [comment]
Hi.  Thanks for your interest in packaging this, but right now I think we have a relatively big show stopper in https://github.com/Blosc/hdf5-blosc/issues/7.   I think it makes sense to wait until this would be sorted out.

**Comment by agardner** [comment]
Is this still waiting on resolution of #7?  Is there any method you can suggest for getting h5py to work with  blosc?

**Comment by FrancescAlted** [comment]
With #7 closed, there should not be any show stopper for releasing the hdf5-blosc as an independent package.  I'll try to update PyTables with hdf5-blosc and latest c-blosc (1.8.1). Could anyone check whether the filter works well in other packages other than PyTables?

**Comment by FrancescAlted** [comment]
In case anyone is willing to help with a new release, #3 and PR #4 offer good hints on what remains to be done.  As always, PR are very welcome.

**Comment by tacaswell** [comment]
@FrancescAlted Those issues have been closed.  What else needs to be done?

**Comment by FrancescAlted** [comment]
Well, I don't think we need anything else other than available developer time ;). I'll try to do that soon.  BTW, if anybody with write privileges for this repo wants to do this too, that's fine with me :)

**Comment by tacaswell** [comment]
If you give me write permissions and a version number it should be I can try :wink: .

**Comment by FrancescAlted** [comment]
Now that you (@tacaswell) are a member of the team, I think a sensible version number for the forthcoming release would be a 1.0.0.  You may want to start with a RC1 if you want give people some opportunity to test the beast before a final release, but it is completely up to you.  Good luck!

**Comment by tacaswell** [comment]
This is getting closer to the top of my to-do list.

**Comment by marscher** [comment]
This issue remains a requirement for https://github.com/conda-forge/staged-recipes/pull/7650

I think it is just the following commands:

git tag v1.1.0 574c7d22265434b90978c0e7aeb5829ad0b19490
git push origin


Thanks for fixing it quickly @tacaswell

**Comment by tacaswell** [comment]
I suspect we want to do a bit more in the way of documentation and collateral than just throwing a tag into the repository.

**Comment by marscher** [comment]
If you can be more specific on what needs to be done, I can submit a PR.

Am 31. Januar 2019 01:08:52 MEZ schrieb Thomas A Caswell <notifications@github.com>:
>I suspect we want to do a bit more in the way of documentation and
>collateral than just throwing a tag into the repository.

**Comment by tacaswell** [comment]
@marscher done!  

@FrancescAlted Thoughts on ret-conning release of:

 v0.0.1 @  fe5ac53050d07c23173bcb8687b85b365acf4620

**Comment by marscher** [comment]
great, thanks a lot!

**Comment by FrancescAlted** [comment]
@tacaswell not sure what the question is sorry.  If you are asking for feedback on using 1.0.0 for the next release, if you guys are happy with that, then I am all for it!

**Comment by tacaswell** [comment]
The v1.0.0 tag is done, my question is if you are ok putting a v0.0.1 tag an that commit (to make the change log make sense!).

**Comment by FrancescAlted** [comment]
Ah, ok.  Yes, I have put the v0.0.1 tag in that commit.  HTH.

**Comment by tacaswell** [comment]
:+1: I'm going to close this as we now have a release!
